### ISSUE TITLE
Promotion Issue

### ISSUE THREAD

**Issue by MikeInnes** [YingboMa/ForwardDiff2.jl#30]
```
julia> using ForwardDiff2

julia> promote(ForwardDiff2.Dual(1, 1), 1)
ERROR: promotion of types ForwardDiff2.Dual{Nothing,Int64,Int64} and Int64 failed to change any arguments
```

**Comment by MikeInnes** [comment]
Unfortunately #32 didn't fix this case. It looks like promotion rules are only defined within the cassette context, but it doesn't actually fix the internal error that I reduced this from either. Happy to provide that case if it's useful.

**Comment by YingboMa** [comment]
Could you give me a MWE?

**Comment by MikeInnes** [comment]
This was the case I was using; not minimal but hopefully you can see what's going on.

```julia
D(x -> x*D(y -> x*y, 1), 4) == 8
```

**Comment by YingboMa** [comment]
```julia
julia> D(x -> D(y -> x*y)(1) * x)(4) * 1
8
```
works for me.

**Comment by MikeInnes** [comment]
Woops, I should have defined

```julia
D(f, x) = ForwardDiff2.D(f)(x)*1
D(x -> x*D(y -> x*y, 1), 4) == 8
```

When I tried your version on master I actually got

```julia
julia> D(x -> D(y -> x*y)(1) * x)(4) * 1
ERROR: * not defined for ForwardDiff2.Dual{ForwardDiff2.Tag{Nothing},Int64,Int64}
```

**Comment by YingboMa** [comment]
Maybe you are using Julia 1.4? FD2 currently only works with 1.3.

**Comment by MikeInnes** [comment]
Indeed, that got it. Thanks a lot for the help.

**Comment by YingboMa** [comment]
You are welcome!

**Comment by MikeInnes** [comment]
Here's a different example (possibly a slightly different issue):

```julia
D(1) do x
  z = D(y -> (x = y), x)
  z * x
end
```

Can you reproduce?

**Comment by YingboMa** [comment]
Oh, that is a tough one. Should be somewhat like #37

**Comment by shashi** [comment]
It's not quite clear what should be done in that case.

```julia
julia> ForwardDiff.derivative(x -> ForwardDiff.derivative(y -> x = y, x)*x, 1)
ERROR: Cannot determine ordering of Dual tags ForwardDiff.Tag{var"#80#82",Int64} and ForwardDiff.Tag{var"#81#83",ForwardDiff.Dual{ForwardDiff.Tag{var"#80#82",Int64},Int64,1}}
Stacktrace:
 [1] partials at /home/shashi/.julia/dev/ForwardDiff/src/dual.jl:106 [inlined]
 [2] extract_derivative(::Type{ForwardDiff.Tag{var"#80#82",Int64}}, ::ForwardDiff.Dual{ForwardDiff.Tag{var"#81#83",ForwardDiff.Dual{ForwardDiff.Tag{var"#80#82",Int64},Int64,1}},ForwardDiff.Dual{ForwardDiff.Tag{var"#80#82",Int64},Int64,1},1}) at /home/shashi/.julia/dev/ForwardDiff/src/derivative.jl:79
 [3] derivative(::var"#80#82", ::Int64) at /home/shashi/.julia/dev/ForwardDiff/src/derivative.jl:14
 [4] top-level scope at REPL[32]:1
 [5] run_backend(::REPL.REPLBackend) at /home/shashi/.julia/packages/Revise/S7mrl/src/Revise.jl:1057
 [6] (::Revise.var"#85#87"{REPL.REPLBackend})() at ./task.jl:333
```

**Comment by MikeInnes** [comment]
> It's not quite clear what should be done in that case.

In principle, or in FD2 specifically? In principle the gradient is `1` (which can be checked in Tracker or Zygote, or by hand). The inner `D(...)` is a no-op (gradient of `1` and it sets `x` to itself) so the expression reduces to `D(x -> 1*x, x)`. (Fun test case right?)

In FD2 I'd assume we'd at least want to fix the promotion error and expose the tag resolution error instead. As much as anything, I've seen a few `PromotionError`s and I don't think they all have this cause; it would be good to be able to distinguish tagging errors from simple missing methods which are easy to fix. That said, thanks to Cassette your PC tags are richer than FD's and I would think you can resolve this case (but I haven't thought in any deep way about tagging so, pinches of salt).

By the way, if it's agreed that there's something to do here it'd be great to open a new issue (I can't myself). I'm also happy to open a new one or whatever as you both see fit, just making sure we don't forget about these cases.
