### ISSUE TITLE
jvp function

### ISSUE THREAD

**Issue by ChrisRackauckas** [YingboMa/ForwardDiff2.jl#7]
Explained in https://mitmath.github.io/18337/lecture9/stiff_odes . Would be a bit better than ForwardDiff because it would use vector/matrix/tensor primitives instead of scalar primitives!

**Comment by oxinabox** [comment]
I sure do hate the abbreviation jvp

**Comment by ChrisRackauckas** [comment]
Well, umm... your variant of English isn't real.

**Comment by oxinabox** [comment]
I am probably going to have to lean to read `vjp`, `jv'p`, ` j⁻¹vp` kind of notation at some point,
it seems like a powerful and precise way to decribe things.

**Comment by ChrisRackauckas** [comment]
jvp is correct, since it's J*v. vjp is the bad one, since it's v'J or J'v.

**Comment by oxinabox** [comment]
Oh man, so people don't even use them precisely?

**Comment by ChrisRackauckas** [comment]
Yeah, there's no such thing as a vjp since a vector cannot left multiply a matrix by a vector unless that matrix is 1xN 🤷‍♂ silly term

**Comment by YingboMa** [comment]
Fixed by #20
